"""
Module for parsing command line arguments
"""

import argparse

from gwemopt.paths import CATALOG_DIR, DEFAULT_LIGHTCURVE_DIR


def parse_args(args):
    parser = argparse.ArgumentParser(
        prog="gwemopt", description="Gravitational-wave Electromagnetic Optimization"
    )

    parser.add_argument("-g", "--gpstime", type=float, help="GPS time.", default=None)

    parser.add_argument(
        "--geometry",
        help="if 3d, check the percentage of KNe recovered by the scheduling. (default: '2d')",
        choices=["2d", "3d"],
        default="2d",
    )

    parser.add_argument(
        "-o",
        "--outputDir",
        help="set the output location of the files generated by gwemopt",
        required=True,
    )
    parser.add_argument(
        "-e",
        "--event",
        help="location of the skymap, could be a local path (eg. /home/skymap/...), a URL where looking for the skymap (eg. https://...) or the event identifier (eg. S170817ab)",
        default=None,
    )

    parser.add_argument("--doCoverage", action="store_true", default=False)

    parser.add_argument("--doSchedule", action="store_true", default=False)
    parser.add_argument("--scheduleType", help="schedule type", default="greedy_slew")
    parser.add_argument(
        "--timeallocationType", help="time allocation type", default="powerlaw"
    )

    parser.add_argument(
        "--plots",
        help="comma delimited list of plot types (skymap,tiles,coverage,schedule,efficiency)",
        default="",
    )
    parser.add_argument("--movie", action="store_true", default=False)
    parser.add_argument("--doTiles", action="store_true", default=False)
    parser.add_argument("--tilesType", help="tiling type", default="moc")
    parser.add_argument("--doMindifFilt", action="store_true", default=False)

    parser.add_argument("--doIterativeTiling", action="store_true", default=False)
    parser.add_argument("--doOverlappingScheduling", action="store_true", default=False)
    parser.add_argument("--doOrderByObservability", action="store_true", default=False)

    parser.add_argument("--catalogDir", help="catalog directory", default=CATALOG_DIR)
    parser.add_argument(
        "--catalog",
        help="Galaxy catalog name",
        default="NOCAT",
        choices=["2MRS", "GLADE", "CLU", "MANGROVE", "NED"],
    )
    parser.add_argument(
        "--galaxy_grade",
        help="grade to use ('S', 'Sloc' or 'Smass')",
        type=str,
        default="S",
        choices=["S", "Sloc", "Smass"],
    )
    parser.add_argument(
        "--powerlaw_dist_exp",
        help="powerlaw exponent used for the distance calculation when using catalogs",
        default=1.0,
        type=float,
    )

    parser.add_argument(
        "--galaxy_limit",
        help="Limit on the number of returned galaxies",
        type=int,
        default=2000,
    )

    parser.add_argument("--doEfficiency", action="store_true", default=False)
    parser.add_argument(
        "-m", "--modelType", help="(file, Bulla, Tophat, afterglow)", default="Tophat"
    )
    parser.add_argument("--mag", help="mag.", default=-16, type=float)
    parser.add_argument("--dmag", help="dmag.", default=0.0, type=float)
    parser.add_argument("-t", "--telescopes", help="Telescope names.", default="ATLAS")
    parser.add_argument(
        "-d",
        "--coverageFiles",
        help="Telescope coverage files.",
        default=None,
    )
    parser.add_argument(
        "-l",
        "--lightcurveFiles",
        help="Lightcurve files.",
        default=DEFAULT_LIGHTCURVE_DIR.joinpath("Me2017_H4M050V20.dat"),
    )
    parser.add_argument(
        "--observedTiles", help="Tiles that have already been observed.", default=""
    )
    parser.add_argument("--Ninj", default=10000, type=int)
    parser.add_argument("--Ntiles", default=10, type=int)

    parser.add_argument("--Ndet", default=1, type=int)
    parser.add_argument("--nside", default=256, type=int)
    parser.add_argument("--Tobs", default="0.0,1.0")

    parser.add_argument("--mindiff", default=0.0, type=float)

    parser.add_argument("--confidence_level", default=1.0, type=float)

    parser.add_argument("--galaxies_FoV_sep", default=1.0, type=float)

    parser.add_argument(
        "--treasuremap_token", help="Treasure Map API Token.", default=None
    )
    parser.add_argument(
        "--treasuremap_status",
        help="Status of Treasure Map observations to be queried.",
        default="planned,completed",
    )

    parser.add_argument("--start_time", default=None)
    parser.add_argument("--end_time", default=None)

    parser.add_argument("-a", "--airmass", default=2.5, type=float)

    parser.add_argument("--doSingleExposure", action="store_true", default=False)
    parser.add_argument("--filters", default="r,g,r")
    parser.add_argument("--doAlternatingFilters", action="store_true", default=False)
    parser.add_argument("--max_filter_sets", default=4, type=int)
    parser.add_argument("--iterativeOverlap", default=0.0, type=float)
    parser.add_argument("--maximumOverlap", default=1.0, type=float)
    parser.add_argument("--doBalanceExposure", action="store_true", default=False)

    parser.add_argument("--exposuretimes", default="30.0,30.0,30.0")

    parser.add_argument("--max_nb_tiles", default=None, type=int)
    parser.add_argument("--doReferences", action="store_true", default=False)

    parser.add_argument("--doChipGaps", action="store_true", default=False)
    parser.add_argument("--doUsePrimary", action="store_true", default=False)
    parser.add_argument("--doUseSecondary", action="store_true", default=False)

    parser.add_argument("--doParallel", action="store_true", default=False)
    parser.add_argument("--Ncores", default=4, type=int)
    parser.add_argument("--parallelBackend", default="threading")

    parser.add_argument(
        "--galactic_limit", help="Galactic limit.", default=0.0, type=float
    )

    parser.add_argument("--ignore_observability", action="store_true", default=False)

    parser.add_argument("--true_location", action="store_true", default=False)
    parser.add_argument("--true_ra", default=30.0, type=float)
    parser.add_argument("--true_dec", default=60.0, type=float)
    parser.add_argument("--true_distance", default=100.0, type=float)
    parser.add_argument("--true_inclination", default=0.0, type=float)

    parser.add_argument("--doTrueLocation", action="store_true", default=False)

    parser.add_argument("--inclination", action="store_true", default=False)
    parser.add_argument("--projection", default="astro mollweide")

    parser.add_argument("--solverType", default="heuristic")
    parser.add_argument("--milpSolver", default="PULP_CBC_CMD")
    parser.add_argument("--milpOptions", default="{}")

    return parser.parse_args(args=args)
